version: 2
jobs:
  # Code testing
  test:
    docker:
      - image: circleci/node:8.11.1
    steps:
      - checkout
      - restore_cache:
          key: node-modules-{{ checksum "package-lock.json" }}
      - run: npm install
      - save_cache:
          key: node-modules-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run: npm test
      - run: npm build
      - persist_to_workspace:
          root: /root/project
          paths: .

  # NPM release
  release:
    docker:
      - image: circleci/node:8.11.1
    steps:
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run: npm publish

workflows:
  version: 2
  build:
    jobs:
      - test
      - release:
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
          requires:
            - test
